package scommons.admin.server

import org.scalatest.DoNotDiscover

@DoNotDiscover
class AdminControllerSpec extends BaseControllersSpec {

  private lazy val commonAssetsUrl = s"$baseUrl/assets/lib/scommons-client-assets"

  it should "load bootstrap.min.css" in {
    //given
    val request = wsUrl(s"$commonAssetsUrl/css/bootstrap.min.css")

    //when
    val response = request.get().futureValue

    //then
    response.status shouldBe 200
    response.contentType shouldBe "text/css; charset=UTF-8"

    response.body should include ("Bootstrap v2.3.1")
  }

  it should "load custom.css" in {
    //given
    val request = wsUrl(s"$commonAssetsUrl/css/custom.css")

    //when
    val response = request.get().futureValue

    //then
    response.status shouldBe 200
    response.contentType shouldBe "text/css; charset=UTF-8"

    response.body should include (".scommons-modal")
  }

  it should "load styles assets generated by webpack" in {
    //given
    val request = wsUrl(s"$baseUrl/assets/styles/scommons-admin-client-fastopt.css")

    //when
    val response = request.get().futureValue

    //then
    response.status shouldBe 200
    response.contentType shouldBe "text/css; charset=UTF-8"

    response.body should include ("background: url(data:image/png;base64")
  }

  it should "load javascript assets generated by webpack" in {
    //given
    val request = wsUrl(s"$baseUrl/assets/scommons-admin-client-fastopt.js")

    //when
    val response = request.get().futureValue

    //then
    response.status shouldBe 200
    response.contentType shouldBe "application/javascript; charset=UTF-8"
  }

  it should "load admin.html page" in {
    //given
    val request = wsUrl(s"$baseUrl/admin.html")

    //when
    val response = request.get().futureValue

    //then
    response.status shouldBe 200
    response.contentType shouldBe "text/html; charset=UTF-8"

    val pageSource = response.body
    pageSource should include (s"$baseUrl/assets/styles/scommons-admin-client-fastopt.css")
    pageSource should include (s"$baseUrl/assets/scommons-admin-client-fastopt-library.js")
    pageSource should include (s"$baseUrl/assets/scommons-admin-client-fastopt-loader.js")
    pageSource should include (s"$baseUrl/assets/scommons-admin-client-fastopt.js")
  }
}
